# Generated by Django 4.1.4 on 2022-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Фрукт',
                'verbose_name_plural': 'Фрукты',
            },
        ),
    ]
